Don't fail on error

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -46,12 +46,12 @@ jobs:
       - name: "Check for changes in Terraform plan"
         id: plan
         run: |
-          # Run in subshell
-          (terraform plan --input=false --detailed-exitcode)
+          terraform plan --input=false --detailed-exitcode \
+            && EXIT_CODE=$? \
+            || EXIT_CODE=$?
 
-          # Check error code
-          EXIT_CODE=$?
-          if (( $ERROR_CODE == 1 )); then
+          # Check exit code
+          if (( $EXIT_CODE == 1 )); then
               exit 1
           fi
 
